"""The mod's item icons, each drawn as a member of its vanilla family (owner, 2026-09-29: "make the book match the
other books in style ... if you want to make a tool, try and match the style of other tools"). On 2026-10-01 the owner
picked nine new icons from the versions on his picker page (ROADMAP 21.1b; round 1's versions are drawn by
tools/textures/picks/):

- boards held level: the blueprint clipped to an oak drawing board, the delivery note's list on a clipboard;
- sheets on the diagonal like the map and paper: the blank blueprint (two sheets); the patrol map and the field marker
  (a field plan) on vanilla's exact map outline (round 2, 2026-10-02);
- the drafting compass on its own, standing on its legs: shape planner;
- an account book lying open: village ledger;
- card held level or hanging from its string: the travel ticket with a sailing boat, the price tag with a dollar sign;
- the stick convention of tools (handle at the bottom-left, head at the top-right): the quarry marker's flag on a
  stake, the scan tool's drafting pencil (round 2);
- held upright, the way vanilla shows its banners: the rally banner's standard;
- a side view: the settler's wagon.

Colours are sampled from vanilla's neighbours; every shape is drawn here (the map outline matches vanilla's, as the
owner asked: "follow the exact outlines minecraft has in place for certain items")."""
from artlib import *  # noqa: F401,F403

# --- Shared materials -----------------------------------------------------------------------------------------------
STICK = P("stick")                  # vanilla stick: outline_light #493615, wood #684e1e / #896727, outline_dark #281e0b
GOLD = P("gold")
PAPER = P("paper")                  # vanilla paper: #c1c1c1 .. #fcfcf2, outline #aeaeae / #878787
IRON = P("iron_tool")               # vanilla iron tools: #6b6b6b .. #ffffff, outline #444444 / #181818
WOOD = {"A": STICK.outline_light, "B": STICK[1], "C": STICK[0], "E": STICK.outline_dark}   # stick letters
OAK = ("#c29d62", "#af8f55", "#967441", "#7e6237", "#614a26", "#382b18")   # oak planks and sign: lit .. dark outline

# Blueprint blue, the same as the Builder's Bench top (builders.py)
BLUE = Ramp(["#244f8f", "#2d5fa6", "#3a6fb8", "#4f86cc"], outline=("#1f467f", "#132d57"), name="blueprint")
INK = "#dce9f7"


def on(base, art, legend):
    """Paints an overlay drawn as ASCII onto a sprite: '.' leaves the pixel below, other letters come from `legend`
    (a colour with alpha 0 punches a hole)."""
    rows = [r.strip() for r in art.strip("\n").split("\n")]
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch not in ". ":
                base.put(x, y, legend[ch])
    return base


# --- Sheets on the diagonal (the map and paper pose) ---------------------------------------------------------------
# A square sheet lying flat, seen from above at an angle: long edges stepping 2-1-2-1, short edges at 45 degrees,
# blunt corners. a = lit outline (the top edges), d = shadow outline (the bottom edges), 3 = the lit band under the
# top edges, 2 = the face, 1 = the shaded band over the bottom edges.
SHEET = """
    ................
    ................
    .........aa.....
    .......aa33a....
    ......a33223a...
    ....aa3222223a..
    ...a3322222223a.
    .aa32222222221d.
    .d1222222221dd..
    ..d12222211d....
    ...d12221dd.....
    ....d121d.......
    .....d1d........
    ......dd........
    ................
    ................
"""

# A smaller sheet in the same pose (long edges stepping 2-1, short edges at 45 degrees), for two to fit in an icon.
SMALL_SHEET = """
    .........aa.....
    .......aa33a....
    ......a33223a...
    ....aa3222223a..
    ...a322222221d..
    ...d1222221dd...
    ....d12221d.....
    .....d121d......
    ......dd........
"""


def sheet(ramp, art=SHEET):
    """A sheet in a ramp of four (shade, face... lit) with its outline pair."""
    return grid(art, {"a": ramp.outline_light, "d": ramp.outline_dark}, ramp=Ramp(list(ramp)[-4:]))


# --- The blueprint family -------------------------------------------------------------------------------------------
def blank_blueprint():
    """Two blank sheets of blueprint paper, one lying on the other (paper and blue dye make two): small sheets on the
    diagonal, the lower one a step darker, in the upper one's shade."""
    under = Ramp([BLUE[0], BLUE[0], BLUE[1], BLUE[2]], outline=(BLUE.outline_light, BLUE.outline_dark))
    s = Sprite()
    s.paste(sheet(under, SMALL_SHEET), 1, 5)
    s.paste(sheet(BLUE, SMALL_SHEET), -1, 2)
    return [s.save(item("blank_blueprint"))]


def blueprint():
    """The blueprint clipped to an oak drawing board, held level: the blue sheet with a white sketch of a house on it
    (a pitched roof over the walls, a chimney and a door) under an iron clip at the top. Also the mod's icon."""
    s = grid("""
        ................
        ......kkkk......
        ..AAAkIIijkAAA..
        ..APPkIiijkPPE..
        ..AP3KKKKKK3qE..
        ..AP322w2w21qE..
        ..AP32w2ww21qE..
        ..AP3w222w21qE..
        ..APwwwwwww1qE..
        ..AP3w222w21qE..
        ..AP3w2w2w21qE..
        ..AP3wwwww21qE..
        ..AP31111111qE..
        ..APqqqqqqqqqE..
        ..EEEEEEEEEEEE..
        ................
    """, dict(WOOD, P=OAK[0], q=OAK[2], w=INK,                                         # board, the house sketch
              I=IRON[3], i="#a8a8a8", j="#727272", k=IRON.outline_light, K="#2b2b2b"),   # the clip
        ramp=BLUE)
    return [s.save(item("blueprint"))]


def shape_planner():
    """A brass drafting compass on its own, standing with its legs apart: a steel point on one foot, a pencil lead on
    the other."""
    s = grid("""
        ................
        .......oo.......
        ......oYyo......
        .....oYyyzo.....
        .....oyzzzO.....
        ......oyzO......
        .....oyOoyO.....
        .....oyO.oyO....
        ....oyO..oyO....
        ....oyO...oyO...
        ...oyO....oyO...
        ...oyO.....oyO..
        ..oyO......gGO..
        ..nN........gG..
        ..n.............
        ................
    """, {"Y": GOLD[3], "y": GOLD[2], "z": GOLD[1], "o": GOLD.outline_light, "O": GOLD.outline_dark,
          "n": "#d8d8d8", "N": "#6b6b6b",                    # the steel point
          "g": "#565664", "G": "#3a3a44"})                   # the pencil lead
    return [s.save(item("shape_planner"))]


# --- Patrol map and field marker: sheets on vanilla's map outline --------------------------------------------------
# Picked by the owner in round 2 (2026-10-02), after his note "make the outline of the paper exact to the paper
# outlines of maps currently in minecraft". The opaque pixels are exactly vanilla's map.png: a square sheet lying on
# the diagonal, its top corner at x 9-10, its left corner at (1, 8), its right corner at (15, 7). The shading is ours,
# in the sheet convention: a = lit outline, d = shadow outline, 3 = the lit band under the top edges, 2 = the face,
# 1 = the band over the bottom edges.
MAP = """
    ................
    ................
    .........aa.....
    ........a33a....
    ......aa3223a...
    .....a3322223a..
    ...aa322222223a.
    ..a332222222221d
    .a122222222221d.
    ..d1222222211d..
    ...d1222221dd...
    ....d12211d.....
    .....d11dd......
    ......dd........
    ................
    ................
"""
# Vanilla's map paper look: lightest in the middle and a step darker towards every edge, darkest at the bottom corner
# (0), on the same outline, in colours sampled from vanilla's map.
MAP_PALE = """
    ................
    ................
    .........aa.....
    ........a22a....
    ......aa2332a...
    .....a2233332a..
    ...aa233333332a.
    ..a223333333321d
    .a123333333321d.
    ..d1233333321d..
    ...d1233321dd...
    ....d11221d.....
    .....d10dd......
    ......dd........
    ................
    ................
"""
VANILLA_MAP = Ramp(["#bbc177", "#daddaa", "#eaeac7", "#fcfcf2"], outline=("#a7a848", "#878839"), name="map paper")
# Parchment for maps: warmer and darker than vanilla's map sheet, outlined in its own browns
PARCHMENT = Ramp(["#cbb57e", "#dccb96", "#eee2b8", "#f8f0d4"], outline=("#a88c4c", "#7a6232"), name="parchment")
ROUTE = "#c02a22"


def vmap(ramp, art=MAP):
    """The vanilla map's sheet in a ramp of four (darkest .. lightest) with its outline pair."""
    return grid(art, {"a": ramp.outline_light, "d": ramp.outline_dark}, ramp=Ramp(list(ramp)[-4:]))


# A blue guard's shield with a gold boss (the guard's colours) at the start of a dashed red loop: the shield sits
# inside the sheet's lower-left half, the loop leaves its top, runs round the wider right half and comes back.
SHIELD = {"k": "#1f3352", "b": BLUE[2], "B": BLUE[3], "Y": GOLD[2], "R": ROUTE}
PATROL = """
    ................
    ................
    ................
    ................
    .........RR.....
    .......R....R...
    ......R......R..
    ....kkkkk.......
    ....kBbbk...R...
    ....kbYbk..R....
    ....kbbbkR......
    .....kbk........
    ......k.........
"""


def patrol_map():
    """The guard's patrol route on vanilla's map paper and outline: a shield where the dashed red loop starts."""
    return [on(vmap(VANILLA_MAP, MAP_PALE), PATROL, SHIELD).save(item("patrol_map"))]


# A field plan: a square plot of green crop rows on tilled soil, a red peg at each of its four corners.
FIELD_PLAN = """
    ................
    ................
    ................
    ................
    .......p........
    ......sGs.......
    .....GsGsG......
    ....sGsGsGs.....
    ...pGsGsGsGp....
    ....sGsGsGs.....
    .....GsGsG......
    ......sGs.......
    .......p........
"""


def field_marker():
    """A field plan on vanilla's map outline, in parchment: crop rows inside four red corner pegs (round 2 pick; he found
    none of round 1's stakes and flags made sense for marking out a field)."""
    return [on(vmap(PARCHMENT), FIELD_PLAN, {"G": "#5a9a2a", "s": "#8a5a2b", "p": ROUTE}).save(item("field_marker"))]


# A city plan: the village's zones painted on the map in their banner colours (white homes, orange workshops, lime
# farms), a grey street running between them and the red hall where it meets the lane.
CITY = """
    ................
    ................
    ................
    ................
    .........ss.....
    ......kk.s.GG...
    .....kwwks.Ggg..
    .....kwwks.Ggg..
    ......kkRRss....
    .....OO.s.......
    ....Ooo.s.......
    .....oo.........
"""


def city_plan():
    """The City Plan (27.2): zones in the map banners' colours on vanilla's map paper and outline, a street and the hall."""
    return [on(vmap(VANILLA_MAP, MAP_PALE), CITY, {"w": "#f4f6f6", "k": "#9da3a3", "o": "#f9801d", "O": "#b85a0e",
                                                   "g": "#80c71f", "G": "#4f7f12", "s": "#8a8a8a", "R": ROUTE}).save(item("city_plan"))]


# --- Paper and card -------------------------------------------------------------------------------------------------
def village_ledger():
    """The hall's account book lying open on its green cloth cover: two pages of vanilla paper ruled into accounts,
    lines of figures and a green column line on each, the pages dipping into the gutter."""
    s = grid("""
        ................
        ..aaa......aaa..
        .a333aa..aa222d.
        ca33333aa22222dc
        caLLLg311LLLg2dc
        ca333g311222g2dc
        caLL3g311LL2g2dc
        ca333g311222g2dc
        caLLLg311LLLg2dc
        ca333g311222g2dc
        caLL3g311LL2g2dc
        cdddd331122ddddc
        kccccdd11ddcccck
        .kkkkkcddckkkkk.
        ......kkkk......
        ................
    """, {"a": PAPER.outline_light, "d": PAPER.outline_dark, "L": "#6e6a80", "g": "#1f9a3c",   # pages, figures
          "c": "#306739", "k": "#0f2a15"},                                                       # the cloth cover
        ramp=PAPER)
    return [s.save(item("village_ledger"))]


def delivery_note():
    """The courier's list on an oak clipboard under an iron clip, two of its jobs ticked off in green."""
    s = grid("""
        ................
        ......iiii......
        ..AAAAiWwiAAAA..
        ..AbbbiwwibbbE..
        ..Ab33iiii22bE..
        ..Ab32222222bE..
        ..Ab3g2LLLL2bE..
        ..Ab22222222bE..
        ..Ab2g2LLL22bE..
        ..Ab22222222bE..
        ..Ab2x2LLLL2bE..
        ..Ab22222222bE..
        ..Ab21111111bE..
        ..AbbbbbbbbbbE..
        ..EEEEEEEEEEEE..
        ................
    """, {"A": OAK[4], "E": OAK[5], "b": OAK[2], "i": IRON.outline_light, "W": IRON[3], "w": IRON[1],
          "L": "#5a5668", "g": "#3f8425", "x": PAPER.outline_light},          # the list's lines, ticks, an open box
        ramp=PAPER)
    return [s.save(item("delivery_note"))]


CREAM = Ramp(["#d4c08e", "#e3d3a8", "#f0e5c4", "#faf4e0"], outline=("#ad9661", "#7f6a3c"), name="card")


def travel_ticket():
    """A cream card ticket held level and notched at both ends: a sailing boat printed on it in two blueprint blues,
    and a stub past the perforation with two lines of print."""
    c = CREAM
    s = grid("""
        ................
        ................
        ................
        ..oooooooooooo..
        .o333N3333p333O.
        .o222Nn2222ii2O.
        ..o22Nnn22p22O..
        ..o22Nnnn222iO..
        ..o22N2222p22O..
        .o2NNNNNNN2ii2O.
        .o11NNNNN1p111O.
        ..OOOOOOOOOOOO..
        ................
        ................
        ................
        ................
    """, {"o": c.outline_light, "O": c.outline_dark, "p": c.outline_light, "i": c.outline_light,   # p perforation
          "N": BLUE[1], "n": BLUE[3]},                                                             # the boat
        ramp=c)
    return [s.save(item("travel_ticket"))]


KRAFT = Ramp(["#b8935a", "#ceac6d", "#e6c78c", "#f2dcaa"], outline=("#8a6a38", "#5c4417"), name="kraft")  # name tag tan


def price_tag():
    """A tan card tag hanging from a white string loop through its hole, a dollar sign printed on it."""
    k = KRAFT
    s = grid("""
        ......SSS.......
        .....S...S......
        ......S.S.......
        .......S........
        .....aaSaa......
        ....a33h22d.....
        ....a32222d.....
        ....a32i21d.....
        ....a2iii1d.....
        ....a3i221d.....
        ....a2iii1d.....
        ....a322i1d.....
        ....a2iii1d.....
        ....a21i11d.....
        .....ddddd......
        ................
    """, {"a": k.outline_light, "d": k.outline_dark, "h": k.outline_dark, "S": "#f7f7f7", "i": "#5c4417"},
        ramp=k)
    return [s.save(item("price_tag"))]


# --- Quarry marker and scan tool: the stick convention (handle at the bottom-left, head at the top-right) ----------
def pad(art, legend, ramp=None):
    """A 16x16 sprite from an ASCII block; missing rows at the bottom are transparent."""
    rows = [r.strip() for r in art.strip().split("\n")]
    rows = [r.ljust(16, ".") for r in rows] + ["." * 16] * (16 - len(rows))
    assert all(len(r) == 16 for r in rows) and len(rows) == 16, "a row wider than 16, or more than 16 rows"
    return Sprite.from_ascii("\n".join(rows), legend, ramp)


# The vanilla stick one row lower, its foot in the bottom-left corner (A lit outline, B/C the wood alternating,
# E shadow outline, EE the cap); its top enters the bottom edge of a flag at row 7.
STICK_BOTTOM = """
    ........ABE.....
    .......ACE......
    ......ABE.......
    .....ACE........
    ....ABE.........
    ...ACE..........
    ..ABE...........
    ..EE............
""".lstrip("\n")

# A flag mounted on top of that stick: 2x2 squares of two cloths (W/R lit, w/r the shaded right column and hem),
# outlined (a lit, d shadow). Square, and with a swallowtail cut into its fly end.
FLAG_SQUARE = """
    ................
    .......aaaaaaad.
    .......aWWRRWWd.
    .......aWWRRWwd.
    .......aRRWWRrd.
    .......aRRWWRrd.
    .......awwrrwwd.
    .......ddACEddd.
""" + STICK_BOTTOM
FLAG_SWALLOWTAIL = """
    ................
    .......aaaaaaaad
    .......aWWRRWWRd
    .......aWWRRWWd.
    .......aRRWWRd..
    .......aRRWWRRd.
    .......awwrrwwrd
    .......ddACEdddd
""" + STICK_BOTTOM
QUARRY = dict(WOOD, W="#f2f2ec", w="#c9c9c0", R="#d9362b", r="#a3241c", a="#7a2a22", d="#4a1a16")


def quarry_marker():
    """A red-and-white chequered swallowtail flag on top of a stake (round 2 pick: "use the stick pattern from the paper
    card with a red x, but this flag")."""
    return [pad(FLAG_SWALLOWTAIL, QUARRY).save(item("quarry_marker"))]


# A drafting pencil on a clean 45-degree line, eraser at the bottom-left, point at the top-right: every row of the
# body is the same 4 px band (f lit outline, g lit face, x a white blueprint line, i shadow outline) one pixel further
# along; the sharpened cedar (t W w T) narrows to a graphite point (K); an iron ferrule (o I m) and a pink eraser.
PENCIL = """
    ................
    ................
    ..............K.
    .............oT.
    ...........tWT..
    ..........tWwT..
    .........fghi...
    ........fghi....
    .......fghi.....
    ......fghi......
    .....fghi.......
    ....oImo........
    ...oImo.........
    ..pPpq..........
    ..qq............
"""
PENCIL_COLOURS = {
    "f": BLUE.outline_light, "g": BLUE[3], "h": BLUE[2], "i": BLUE.outline_dark, "x": INK,   # blueprint blue
    "W": "#ecd5a4", "w": "#cfab6c", "t": "#9c7a44", "T": "#6b5328",                           # cedar, sharpened
    "K": "#2e2e36",                                                                           # graphite
    "o": "#727272", "I": "#d8d8d8", "m": "#a8a8a8",                                           # iron ferrule
    "P": "#f4a7c0", "p": "#e07a9e", "q": "#9c3c5c",                                           # pink eraser
}


def scan_tool():
    """A blueprint-blue drafting pencil with a white blueprint line, sharpened to a point (round 2 pick: "straighten out
    line, make it more obviously a pencil with the tip coming to a point")."""
    return [pad(PENCIL.replace("fghi", "fgxi"), PENCIL_COLOURS).save(item("scan_tool"))]


# --- Rally Banner: held upright like vanilla's banners ----------------------------------------------------------------
def rally_banner():
    """A tall standard held upright, the way vanilla shows its banners: an iron crossbar with a gold finial, a blue
    cloth with two crossed swords (gold guards, wooden grips) and a tattered hem, the foot of the pole below."""
    s = grid("""
        .......yY.......
        ...xxxxxxxxxx...
        ...nVuuuuuuVN...
        ...nuVuuuuVUN...
        ...nuuVuuVUUN...
        ...nuuuVVUUUN...
        ...nuuuVVUUUN...
        ...nuuVuuVUUN...
        ...nuVuuuuVUN...
        ...nyyyuuyyyN...
        ...nutuuuuUtN...
        ...nuuuuUUUUN...
        ...nunuuNUNUN...
        ...nn.nNN.NNN...
        .......AE.......
        .......EE.......
    """, dict(WOOD, n="#1f2f6a", N="#141d45", u="#3e4db2", U="#2d3a90", V="#f2f2ec",   # blue wool, silver blades
              y=GOLD[2], Y=GOLD[0], x="#6b6b6b", t="#5a3a18"))                            # guards, crossbar, grips
    return [s.save(item("rally_banner"))]


# --- Settler's Wagon: a side view -----------------------------------------------------------------------------------
def settlers_wagon():
    """A covered wagon in side view, facing right: the canvas bonnet with its hoops showing, a plank bed, two spoked
    wheels and the stub of the pole."""
    s = grid("""
        ................
        ................
        ....VVVVVVVV....
        ...VWWWWWWWWV...
        ..VWWvWWvWWvwV..
        ..VWwvwwvwwvwV..
        ..VwwvwwvwwvwV..
        ..VwwvwwvwwvvX..
        .OPPPPPPPPPPPPO.
        .OppppppppppppQQ
        ..kkkQQQQQkkkQ..
        .kkhkk...kkhkk..
        .khhhk...khhhk..
        .kkhkk...kkhkk..
        ..kkk.....kkk...
        ................
    """, {"W": "#f6f2e6", "w": "#e4ddc9", "v": "#c8bfa6", "V": "#8f866e", "X": "#5f5846",   # canvas
          "P": OAK[1], "p": OAK[2], "O": "#4a3a18", "Q": "#2e260c",                       # oak bed
          "k": "#3a2712", "h": OAK[0]})                                                   # wheels: rims, spokes
    return [s.save(item("settlers_wagon"))]


def guide_book():
    """The Guide Book (ROADMAP 26.2a): vanilla's book, on its exact outline, pages and shading, bound in blueprint blue
    with a gold house stamped on the cover (in place of vanilla's tooled lines), so it reads as a book and as this
    mod's."""
    s = grid("""
        ................
        ........aaa.....
        ......aabcda....
        ....aabccccca...
        ..aabccccYccca..
        aabdccccYYYccda.
        abdcccccYyYcccea
        aabccccccccceef.
        aagbcccccceehgh.
        ibjgbdcceehgghae
        .ibjgbeehgghaeii
        ..ibjghgghaeii..
        ...ibjgheeii....
        ....ibeeii......
        .....iii........
        ................
    """, {"a": "#13254a", "i": "#0a1428",                          # outline: navy, darkest underneath
          "b": BLUE[0], "d": BLUE[1], "c": BLUE[2], "e": BLUE.outline_light,   # the cover, shaded as vanilla's
          "Y": GOLD[3], "y": GOLD[1],                              # the gold house and its door
          "f": "#5b5b5b", "g": "#b7b7b7", "h": "#999999", "j": "#d6d6d6"})     # the pages (vanilla's greys)
    return [s.save(item("guide_book"))]


# Goat horn: the grey-brown of vanilla's horn (sampled), lit .. dark, and its outlines.
HORN = Ramp(["#3c3633", "#544f4a", "#6e6a63", "#8e8a7f", "#aaa898"], outline=("#4a4643", "#2a2725"), name="horn")


def work_horn():
    """The Work Horn (30.11), drawn as vanilla draws its goat horn: the horn lying with its mouth up at the top-left
    and its curl sweeping down and back up to the tip at the right, here bound in two brass bands with a brass
    mouthpiece cap on the tip (the gold ingot of its recipe)."""
    s = grid("""
        ................
        ................
        ..aaaaa.........
        .a34443a........
        .a3kkk3d........
        .a33222d........
        .zYYYYyz........
        .a33221d........
        ..a3321d....zz..
        ..a33221a..zYwz.
        ...zYYyy1aazyyz.
        ...azYy2211a22d.
        ....d22221111d..
        .....dd11111d...
        .......dddd.....
        ................
    """, {"a": HORN.outline_light, "d": HORN.outline_dark, "k": "#1e1b19",
          "Y": GOLD[2], "y": GOLD[0], "w": GOLD[3], "z": GOLD.outline_light},
        ramp=HORN)
    return [s.save(item("work_horn"))]


DRAW = [blank_blueprint, blueprint, shape_planner, patrol_map, delivery_note, travel_ticket, price_tag,
        village_ledger, field_marker, city_plan, quarry_marker, rally_banner, scan_tool, settlers_wagon, guide_book,
        work_horn]

if __name__ == "__main__":
    run(DRAW)
