"""The mod's item icons, each drawn as a member of its vanilla family (owner, 2026-09-29: "make the book match the
other books in style ... if you want to make a tool, try and match the style of other tools"):

- sheets lying on the diagonal like the map and paper: blank blueprint, blueprint, shape planner, patrol map,
  delivery note, travel ticket;
- the book pose: village ledger;
- the name tag's pose: price tag;
- the stick convention of tools (handle at the bottom-left, head at the top-right): field and quarry markers,
  rally banner, scan tool;
- the minecart's 3/4 view: settler's wagon.

Colours are sampled from vanilla's neighbours; every shape is drawn here."""
from artlib import *  # noqa: F401,F403

# --- Shared materials -----------------------------------------------------------------------------------------------
STICK = P("stick")                  # vanilla stick: outline_light #493615, wood #684e1e / #896727, outline_dark #281e0b
LEATHER = P("leather")
GOLD = P("gold")
PAPER = P("paper")                  # vanilla paper: #c1c1c1 .. #fcfcf2, outline #aeaeae / #878787
WOOD = {"A": STICK.outline_light, "B": STICK[1], "C": STICK[0], "E": STICK.outline_dark}   # stick letters

# Blueprint blue, the same as the Builder's Bench top (builders.py)
BLUE = Ramp(["#244f8f", "#2d5fa6", "#3a6fb8", "#4f86cc"], outline=("#1f467f", "#132d57"), name="blueprint")
INK = "#dce9f7"


def on(base, art, legend):
    """Paints an overlay drawn as ASCII onto a sprite: '.' leaves the pixel below, other letters come from `legend`
    (a colour with alpha 0 punches a hole)."""
    rows = [r.strip() for r in art.strip("\n").split("\n")]
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch not in ". ":
                base.put(x, y, legend[ch])
    return base


# --- Sheets on the diagonal (the map and paper pose) ---------------------------------------------------------------
# A square sheet lying flat, seen from above at an angle: long edges stepping 2-1-2-1, short edges at 45 degrees,
# blunt corners. a = lit outline (the top edges), d = shadow outline (the bottom edges), 3 = the lit band under the
# top edges, 2 = the face, 1 = the shaded band over the bottom edges.
SHEET = """
    ................
    ................
    .........aa.....
    .......aa33a....
    ......a33223a...
    ....aa3222223a..
    ...a3322222223a.
    .aa32222222221d.
    .d1222222221dd..
    ..d12222211d....
    ...d12221dd.....
    ....d121d.......
    .....d1d........
    ......dd........
    ................
    ................
"""


def sheet(ramp, art=SHEET):
    """A sheet in a ramp of four (shade, face... lit) with its outline pair."""
    return grid(art, {"a": ramp.outline_light, "d": ramp.outline_dark}, ramp=Ramp(list(ramp)[-4:]))


def blank_blueprint():
    """An empty sheet of blueprint paper, plain like vanilla's empty map (a blind test read it as blue paper with or
    without a drafting border, so it stays empty as asked)."""
    return [sheet(BLUE).save(item("blank_blueprint"))]


def blueprint():
    """The blueprint sheet with a white sketch of a house on it: a pitched roof over the walls, a chimney and a door."""
    s = on(sheet(BLUE), """
        ................
        ................
        ................
        ................
        ........w.w.....
        .......w.ww.....
        ......w...w.....
        .....wwwwwww....
        ......w...w.....
        ......w.w.w.....
        ......wwwww.....
    """, {"w": INK})
    return [s.save(item("blueprint"))]


def shape_planner():
    """The blueprint sheet with a dome drawn on it and a brass drafting compass standing on it, legs apart."""
    s = on(sheet(BLUE), """
        ................
        ...........oo...
        ..........oYyo..
        ..........okzo..
        .........ok.ozo.
        .........ok.ozo.
        .....www.ok..ozo
        ....w...wok..ozo
        ...w.....Nn...Nn
        ...wwwwwww......
    """, {"w": INK, "Y": GOLD[3], "y": GOLD[2], "k": GOLD[2], "z": GOLD[1], "o": GOLD.outline_light,
          "n": "#e6e6e6", "N": "#8a8a8a"})                     # n, N: the steel points of the legs
    return [s.save(item("shape_planner"))]


# Parchment for maps: warmer and darker than vanilla's map sheet, outlined in its own browns
PARCHMENT = Ramp(["#cbb57e", "#dccb96", "#eee2b8", "#f8f0d4"], outline=("#a88c4c", "#7a6232"), name="parchment")
ROUTE = "#c02a22"


def patrol_map():
    """A parchment map with a dotted red route between two blue marker flags."""
    s = on(sheet(PARCHMENT), """
        ................
        ................
        ................
        ................
        ..........Fbb...
        ..........Fb....
        ........R.F.....
        ................
        ....Fb.R........
        ....F...........
    """, {"F": "#4a3218", "b": BLUE[2], "R": ROUTE})
    return [s.save(item("patrol_map"))]


# --- Paper and card on the diagonal ---------------------------------------------------------------------------------
# An envelope: the sheet's pose, longer than it is wide (long edges step 2 px a row).
ENVELOPE = """
    ................
    ................
    ................
    ................
    ..........aa....
    ........aa33a...
    ......aa33223a..
    ....aa33222223a.
    ..aa3322222221d.
    .a1222222221dd..
    ..d1222221dd....
    ...d1221dd......
    ....d11d........
    .....dd.........
    ................
    ................
"""


def delivery_note():
    """A letter in vanilla paper, sealed with red wax where the two edges of the flap meet."""
    s = on(sheet(PAPER, ENVELOPE), """
        ................
        ................
        ................
        ................
        ................
        ................
        ...........f....
        ..........f.....
        ....ff...f......
        ......fRr.......
        .......rq.......
    """, {"f": PAPER.outline_light, "r": "#c62d25", "R": "#ef6b5b", "q": "#861a15"})
    return [s.save(item("delivery_note"))]


CREAM = Ramp(["#d4c08e", "#e3d3a8", "#f0e5c4", "#faf4e0"], outline=("#ad9661", "#7f6a3c"), name="card")
TICKET_GOLD = Ramp(["#c9931f", "#e9b53a", "#f4cf5e"], outline=("#a8741a", "#6e4a0e"), name="gold card")


def travel_ticket():
    """A gold card ticket lying on the diagonal like paper, flat like a card: a cream stub past a perforated line at
    the top-right, two lines of print and a hole punched near the other end."""
    t, c = TICKET_GOLD, CREAM
    s = grid("""
        ................
        ................
        ................
        ................
        ..........oo....
        ........ooBBq...
        ......ooBBpSSq..
        ....ooBBbbpssSq.
        ..ooBbxxbbpssQQ.
        .oBkbbbbbbpQQ...
        .OkhbxxbbOO.....
        ..ObbbbOO.......
        ...ObbO.........
        ....OO..........
        ................
        ................
    """, {"b": t[1], "B": t[2], "o": t.outline_light, "O": t.outline_dark, "x": t.outline_light, "p": t[0],
          "k": t.outline_dark, "h": "#00000000",
          "s": c[2], "S": c[3], "q": c.outline_light, "Q": c.outline_dark})
    return [s.save(item("travel_ticket"))]


# --- Price Tag: the name tag's pose ---------------------------------------------------------------------------------
def price_tag():
    """A white paper tag cut to a point at the top-right, a red string looped through its hole, a gold coin on it.
    Vanilla's name tag is a tan strip on a silver hook: this one is shorter, pointed, white and on a string."""
    tag = Ramp(list(PAPER), outline=("#9a9a9a", "#6e6e6e"), name="tag")
    s = grid("""
        ................
        ................
        ............rrq.
        ...........r...q
        ...........r...q
        .........aaar..q
        ........a33krqq.
        .......a32kh1d..
        ......a322221d..
        .....a322oo21d..
        ....a32oYyo1d...
        ...a322oyzo1d...
        ....d122oo1d....
        .....d1221d.....
        ......d11d......
        .......dd.......
    """, {"a": tag.outline_light, "d": tag.outline_dark, "k": tag.outline_dark, "h": "#00000000",
          "r": "#c62d25", "q": "#8e1c16", "o": GOLD.outline_light, "Y": GOLD[2], "y": GOLD[1], "z": GOLD[0]},
        ramp=tag)
    return [s.save(item("price_tag"))]


# --- Village Ledger: the book pose ---------------------------------------------------------------------------------
def village_ledger():
    """The hall's account book, lying on the diagonal like vanilla's books. A green cloth cover with leather corners
    and a small gold label, a gold clasp strapped over the pages, the page block thicker than a book's, and a red
    ribbon hanging out of it."""
    green = Ramp(["#27552f", "#306739", "#3e7c48"], name="ledger cloth")   # digits: 0 shade, 1 face, 2 lit
    s = grid("""
        ................
        ........a.......
        ......aa2a......
        ....aa2211a.....
        ..aa2211111a....
        aa221YYy1111a...
        pa2111yyz110la..
        qpb11111110lLa..
        Oqpb111100ybLpp.
        .Oqpb1100bYppqq.
        ..OrpLlLbpyqqOO.
        ...rqpLppqzOO...
        ...ROqpqqOO.....
        .....OqOO.......
        ......O.........
        ................
    """, {
        "a": "#173d1f", "b": "#0f2a15", "O": "#0c1f0f",          # cover edges (lit / shadow) and the back cover
        "p": "#d6d6d6", "q": "#b7b7b7",                           # page edges
        "l": LEATHER[2], "L": LEATHER[0],                         # leather corners
        "Y": GOLD[2], "y": GOLD[1], "z": GOLD.outline_light,      # label and clasp
        "r": "#b8342c", "R": "#902120",                           # ribbon
    }, ramp=green)
    return [s.save(item("village_ledger"))]


# --- Stakes and poles: the stick convention --------------------------------------------------------------------------
def field_marker():
    """A wooden stake (the vanilla stick) with a small green swallowtail flag at the top."""
    s = grid("""
        ................
        ..........AE....
        .........ABoooo.
        ........ACogggoo
        .......ABEofffgo
        ......ACE.offffo
        .....ABE..ofsoso
        ....ACE...oo.oo.
        ...ABE..........
        ..ACE...........
        .ABE............
        .AE.............
        .E..............
        ................
        ................
        ................
    """, dict(WOOD, g="#7fcc4a", f="#5aa832", s="#3f8425", o="#1f4a14"))
    return [s.save(item("field_marker"))]


def quarry_marker():
    """A wooden stake with a small red and white chequered swallowtail flag at the top."""
    s = grid("""
        ................
        ..........AE....
        .........ABoooo.
        ........ACowwrro
        .......ABEowvrqo
        ......ACE.orrwvo
        .....ABE..oqqvvo
        ....ACE...oo.oo.
        ...ABE..........
        ..ACE...........
        .ABE............
        .AE.............
        .E..............
        ................
        ................
        ................
    """, dict(WOOD, r="#d9362b", q="#a3241c", w="#f2f2ec", v="#c9c9c0", o="#4a1a16"))
    return [s.save(item("quarry_marker"))]


def rally_banner():
    """A war banner carried like a tool: the pole from the bottom-left, a brass crossbar with a gold finial, red cloth
    hanging from it with a gold crown and a swallowtail hem."""
    s = grid("""
        ................
        ................
        ..........YX....
        ......xxxxxxxxX.
        ......orrrrrrfo.
        ......oryrYryfo.
        .....Aoryyyyyfo.
        ....ABorzzzzzfo.
        ...ACEofrrrrffo.
        ..ABE.offffffso.
        .ACE..offsosfso.
        ABE...ofso.ofso.
        EE....oo.....oo.
        ................
        ................
        ................
    """, dict(WOOD, r="#c8302c", f="#a8201f", s="#86181a", o="#4a0c0c",
              y=GOLD[2], Y=GOLD[3], z=GOLD[1], x=GOLD.outline_light, X=GOLD.outline_dark))
    return [s.save(item("rally_banner"))]


def scan_tool():
    """A surveyor's wand held like a tool: a blue rod (the stick's pattern in blue) with a brass butt cap and ferrule,
    a brass collar at the top holding a violet crystal."""
    am = P("amethyst")
    s = grid("""
        ................
        .............oo.
        ............oWco
        ...........oceWo
        ..........Zyefco
        .........ZYyzfo.
        ........ZYzzQo..
        .......ABzQQ....
        ......ACE.......
        .....ZYQ........
        ....ACE.........
        ...ABE..........
        ..ACE...........
        .ZyQ............
        .QQ.............
        ................
    """, {"A": BLUE.outline_light, "B": BLUE[3], "C": BLUE[2], "E": BLUE.outline_dark,
          "Y": GOLD[3], "y": GOLD[2], "z": GOLD[1], "Z": GOLD.outline_light, "Q": GOLD.outline_dark,
          "W": am[5], "c": am[3], "e": am[2], "f": am[1], "o": am.outline_dark})
    return [s.save(item("scan_tool"))]


# --- Settler's Wagon: the minecart's 3/4 view ------------------------------------------------------------------------
def settlers_wagon():
    """A covered wagon seen from above and to the front-left like vanilla's minecarts: a canvas bonnet with its hoops
    showing, the open back dark inside, a plank bed and two spoked wheels (the front one with the stub of its pole)."""
    s = grid("""
        ................
        ................
        ....VVV.........
        ..VVWWWVV.......
        .VWWWWwwwVV.....
        .VWWvwwwwwwVV...
        .VWvwwwwvwwWVV..
        .VWvwwwwvwWIIIV.
        .OPPPwwwvWIIiIX.
        .OpppPPPPWIIIIX.
        ..kkkpppPPPPPX..
        .kKhKkqqpqqqX...
        OkhhhkOkkkQQ....
        .kKhKkkKhKk.....
        ..kkk.khhhk.....
        ......kKhKk.....
    """, {"W": "#f6f2e6", "w": "#e4ddc9", "v": "#c8bfa6", "V": "#8f866e", "X": "#5f5846",   # canvas
          "i": "#6b4a2a", "I": "#4a321c",                                                   # inside
          "P": "#af8f55", "p": "#967441", "q": "#7e6237", "O": "#4a3a18", "Q": "#2e260c",   # oak bed
          "k": "#3a2712", "K": "#241808", "h": "#c29d62"})                                  # wheels
    return [s.save(item("settlers_wagon"))]


DRAW = [blank_blueprint, blueprint, shape_planner, patrol_map, delivery_note, travel_ticket, price_tag,
        village_ledger, field_marker, quarry_marker, rally_banner, scan_tool, settlers_wagon]

if __name__ == "__main__":
    run(DRAW)
