"""The mod's item icons, each drawn as a member of its vanilla family (owner, 2026-09-29: "make the book match the
other books in style ... if you want to make a tool, try and match the style of other tools"). On 2026-10-01 the owner
picked nine new icons from the versions on his picker page (ROADMAP 21.1b; round 1's versions are drawn by
tools/textures/picks/):

- boards held level: the blueprint clipped to an oak drawing board, the delivery note's list on a clipboard;
- sheets on the diagonal like the map and paper: the blank blueprint (two sheets), the patrol map;
- the drafting compass on its own, standing on its legs: shape planner;
- an account book lying open: village ledger;
- card held level or hanging from its string: the travel ticket with a sailing boat, the price tag with a dollar sign;
- the stick convention of tools (handle at the bottom-left, head at the top-right): field and quarry markers, scan tool;
- held upright, the way vanilla shows its banners: the rally banner's standard;
- a side view: the settler's wagon.

The patrol map, quarry marker, scan tool and field marker are still the 2026-09-29 icons; they get a second round of
picks. Colours are sampled from vanilla's neighbours; every shape is drawn here."""
from artlib import *  # noqa: F401,F403

# --- Shared materials -----------------------------------------------------------------------------------------------
STICK = P("stick")                  # vanilla stick: outline_light #493615, wood #684e1e / #896727, outline_dark #281e0b
GOLD = P("gold")
PAPER = P("paper")                  # vanilla paper: #c1c1c1 .. #fcfcf2, outline #aeaeae / #878787
IRON = P("iron_tool")               # vanilla iron tools: #6b6b6b .. #ffffff, outline #444444 / #181818
WOOD = {"A": STICK.outline_light, "B": STICK[1], "C": STICK[0], "E": STICK.outline_dark}   # stick letters
OAK = ("#c29d62", "#af8f55", "#967441", "#7e6237", "#614a26", "#382b18")   # oak planks and sign: lit .. dark outline

# Blueprint blue, the same as the Builder's Bench top (builders.py)
BLUE = Ramp(["#244f8f", "#2d5fa6", "#3a6fb8", "#4f86cc"], outline=("#1f467f", "#132d57"), name="blueprint")
INK = "#dce9f7"


def on(base, art, legend):
    """Paints an overlay drawn as ASCII onto a sprite: '.' leaves the pixel below, other letters come from `legend`
    (a colour with alpha 0 punches a hole)."""
    rows = [r.strip() for r in art.strip("\n").split("\n")]
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch not in ". ":
                base.put(x, y, legend[ch])
    return base


# --- Sheets on the diagonal (the map and paper pose) ---------------------------------------------------------------
# A square sheet lying flat, seen from above at an angle: long edges stepping 2-1-2-1, short edges at 45 degrees,
# blunt corners. a = lit outline (the top edges), d = shadow outline (the bottom edges), 3 = the lit band under the
# top edges, 2 = the face, 1 = the shaded band over the bottom edges.
SHEET = """
    ................
    ................
    .........aa.....
    .......aa33a....
    ......a33223a...
    ....aa3222223a..
    ...a3322222223a.
    .aa32222222221d.
    .d1222222221dd..
    ..d12222211d....
    ...d12221dd.....
    ....d121d.......
    .....d1d........
    ......dd........
    ................
    ................
"""

# A smaller sheet in the same pose (long edges stepping 2-1, short edges at 45 degrees), for two to fit in an icon.
SMALL_SHEET = """
    .........aa.....
    .......aa33a....
    ......a33223a...
    ....aa3222223a..
    ...a322222221d..
    ...d1222221dd...
    ....d12221d.....
    .....d121d......
    ......dd........
"""


def sheet(ramp, art=SHEET):
    """A sheet in a ramp of four (shade, face... lit) with its outline pair."""
    return grid(art, {"a": ramp.outline_light, "d": ramp.outline_dark}, ramp=Ramp(list(ramp)[-4:]))


# --- The blueprint family -------------------------------------------------------------------------------------------
def blank_blueprint():
    """Two blank sheets of blueprint paper, one lying on the other (paper and blue dye make two): small sheets on the
    diagonal, the lower one a step darker, in the upper one's shade."""
    under = Ramp([BLUE[0], BLUE[0], BLUE[1], BLUE[2]], outline=(BLUE.outline_light, BLUE.outline_dark))
    s = Sprite()
    s.paste(sheet(under, SMALL_SHEET), 1, 5)
    s.paste(sheet(BLUE, SMALL_SHEET), -1, 2)
    return [s.save(item("blank_blueprint"))]


def blueprint():
    """The blueprint clipped to an oak drawing board, held level: the blue sheet with a white sketch of a house on it
    (a pitched roof over the walls, a chimney and a door) under an iron clip at the top. Also the mod's icon."""
    s = grid("""
        ................
        ......kkkk......
        ..AAAkIIijkAAA..
        ..APPkIiijkPPE..
        ..AP3KKKKKK3qE..
        ..AP322w2w21qE..
        ..AP32w2ww21qE..
        ..AP3w222w21qE..
        ..APwwwwwww1qE..
        ..AP3w222w21qE..
        ..AP3w2w2w21qE..
        ..AP3wwwww21qE..
        ..AP31111111qE..
        ..APqqqqqqqqqE..
        ..EEEEEEEEEEEE..
        ................
    """, dict(WOOD, P=OAK[0], q=OAK[2], w=INK,                                         # board, the house sketch
              I=IRON[3], i="#a8a8a8", j="#727272", k=IRON.outline_light, K="#2b2b2b"),   # the clip
        ramp=BLUE)
    return [s.save(item("blueprint"))]


def shape_planner():
    """A brass drafting compass on its own, standing with its legs apart: a steel point on one foot, a pencil lead on
    the other."""
    s = grid("""
        ................
        .......oo.......
        ......oYyo......
        .....oYyyzo.....
        .....oyzzzO.....
        ......oyzO......
        .....oyOoyO.....
        .....oyO.oyO....
        ....oyO..oyO....
        ....oyO...oyO...
        ...oyO....oyO...
        ...oyO.....oyO..
        ..oyO......gGO..
        ..nN........gG..
        ..n.............
        ................
    """, {"Y": GOLD[3], "y": GOLD[2], "z": GOLD[1], "o": GOLD.outline_light, "O": GOLD.outline_dark,
          "n": "#d8d8d8", "N": "#6b6b6b",                    # the steel point
          "g": "#565664", "G": "#3a3a44"})                   # the pencil lead
    return [s.save(item("shape_planner"))]


# --- Patrol map: a sheet on the diagonal ----------------------------------------------------------------------------
# Parchment for maps: warmer and darker than vanilla's map sheet, outlined in its own browns
PARCHMENT = Ramp(["#cbb57e", "#dccb96", "#eee2b8", "#f8f0d4"], outline=("#a88c4c", "#7a6232"), name="parchment")
ROUTE = "#c02a22"


def patrol_map():
    """A parchment map with a dotted red route between two blue marker flags."""
    s = on(sheet(PARCHMENT), """
        ................
        ................
        ................
        ................
        ..........Fbb...
        ..........Fb....
        ........R.F.....
        ................
        ....Fb.R........
        ....F...........
    """, {"F": "#4a3218", "b": BLUE[2], "R": ROUTE})
    return [s.save(item("patrol_map"))]


# --- Paper and card -------------------------------------------------------------------------------------------------
def village_ledger():
    """The hall's account book lying open on its green cloth cover: two pages of vanilla paper ruled into accounts,
    lines of figures and a green column line on each, the pages dipping into the gutter."""
    s = grid("""
        ................
        ..aaa......aaa..
        .a333aa..aa222d.
        ca33333aa22222dc
        caLLLg311LLLg2dc
        ca333g311222g2dc
        caLL3g311LL2g2dc
        ca333g311222g2dc
        caLLLg311LLLg2dc
        ca333g311222g2dc
        caLL3g311LL2g2dc
        cdddd331122ddddc
        kccccdd11ddcccck
        .kkkkkcddckkkkk.
        ......kkkk......
        ................
    """, {"a": PAPER.outline_light, "d": PAPER.outline_dark, "L": "#6e6a80", "g": "#1f9a3c",   # pages, figures
          "c": "#306739", "k": "#0f2a15"},                                                       # the cloth cover
        ramp=PAPER)
    return [s.save(item("village_ledger"))]


def delivery_note():
    """The courier's list on an oak clipboard under an iron clip, two of its jobs ticked off in green."""
    s = grid("""
        ................
        ......iiii......
        ..AAAAiWwiAAAA..
        ..AbbbiwwibbbE..
        ..Ab33iiii22bE..
        ..Ab32222222bE..
        ..Ab3g2LLLL2bE..
        ..Ab22222222bE..
        ..Ab2g2LLL22bE..
        ..Ab22222222bE..
        ..Ab2x2LLLL2bE..
        ..Ab22222222bE..
        ..Ab21111111bE..
        ..AbbbbbbbbbbE..
        ..EEEEEEEEEEEE..
        ................
    """, {"A": OAK[4], "E": OAK[5], "b": OAK[2], "i": IRON.outline_light, "W": IRON[3], "w": IRON[1],
          "L": "#5a5668", "g": "#3f8425", "x": PAPER.outline_light},          # the list's lines, ticks, an open box
        ramp=PAPER)
    return [s.save(item("delivery_note"))]


CREAM = Ramp(["#d4c08e", "#e3d3a8", "#f0e5c4", "#faf4e0"], outline=("#ad9661", "#7f6a3c"), name="card")


def travel_ticket():
    """A cream card ticket held level and notched at both ends: a sailing boat printed on it in two blueprint blues,
    and a stub past the perforation with two lines of print."""
    c = CREAM
    s = grid("""
        ................
        ................
        ................
        ..oooooooooooo..
        .o333N3333p333O.
        .o222Nn2222ii2O.
        ..o22Nnn22p22O..
        ..o22Nnnn222iO..
        ..o22N2222p22O..
        .o2NNNNNNN2ii2O.
        .o11NNNNN1p111O.
        ..OOOOOOOOOOOO..
        ................
        ................
        ................
        ................
    """, {"o": c.outline_light, "O": c.outline_dark, "p": c.outline_light, "i": c.outline_light,   # p perforation
          "N": BLUE[1], "n": BLUE[3]},                                                             # the boat
        ramp=c)
    return [s.save(item("travel_ticket"))]


KRAFT = Ramp(["#b8935a", "#ceac6d", "#e6c78c", "#f2dcaa"], outline=("#8a6a38", "#5c4417"), name="kraft")  # name tag tan


def price_tag():
    """A tan card tag hanging from a white string loop through its hole, a dollar sign printed on it."""
    k = KRAFT
    s = grid("""
        ......SSS.......
        .....S...S......
        ......S.S.......
        .......S........
        .....aaSaa......
        ....a33h22d.....
        ....a32222d.....
        ....a32i21d.....
        ....a2iii1d.....
        ....a3i221d.....
        ....a2iii1d.....
        ....a322i1d.....
        ....a2iii1d.....
        ....a21i11d.....
        .....ddddd......
        ................
    """, {"a": k.outline_light, "d": k.outline_dark, "h": k.outline_dark, "S": "#f7f7f7", "i": "#5c4417"},
        ramp=k)
    return [s.save(item("price_tag"))]


# --- Stakes and poles: the stick convention --------------------------------------------------------------------------
def field_marker():
    """A wooden stake (the vanilla stick) with a small green swallowtail flag at the top."""
    s = grid("""
        ................
        ..........AE....
        .........ABoooo.
        ........ACogggoo
        .......ABEofffgo
        ......ACE.offffo
        .....ABE..ofsoso
        ....ACE...oo.oo.
        ...ABE..........
        ..ACE...........
        .ABE............
        .AE.............
        .E..............
        ................
        ................
        ................
    """, dict(WOOD, g="#7fcc4a", f="#5aa832", s="#3f8425", o="#1f4a14"))
    return [s.save(item("field_marker"))]


def quarry_marker():
    """A wooden stake with a small red and white chequered swallowtail flag at the top."""
    s = grid("""
        ................
        ..........AE....
        .........ABoooo.
        ........ACowwrro
        .......ABEowvrqo
        ......ACE.orrwvo
        .....ABE..oqqvvo
        ....ACE...oo.oo.
        ...ABE..........
        ..ACE...........
        .ABE............
        .AE.............
        .E..............
        ................
        ................
        ................
    """, dict(WOOD, r="#d9362b", q="#a3241c", w="#f2f2ec", v="#c9c9c0", o="#4a1a16"))
    return [s.save(item("quarry_marker"))]


def scan_tool():
    """A surveyor's wand held like a tool: a blue rod (the stick's pattern in blue) with a brass butt cap and ferrule,
    a brass collar at the top holding a violet crystal."""
    am = P("amethyst")
    s = grid("""
        ................
        .............oo.
        ............oWco
        ...........oceWo
        ..........Zyefco
        .........ZYyzfo.
        ........ZYzzQo..
        .......ABzQQ....
        ......ACE.......
        .....ZYQ........
        ....ACE.........
        ...ABE..........
        ..ACE...........
        .ZyQ............
        .QQ.............
        ................
    """, {"A": BLUE.outline_light, "B": BLUE[3], "C": BLUE[2], "E": BLUE.outline_dark,
          "Y": GOLD[3], "y": GOLD[2], "z": GOLD[1], "Z": GOLD.outline_light, "Q": GOLD.outline_dark,
          "W": am[5], "c": am[3], "e": am[2], "f": am[1], "o": am.outline_dark})
    return [s.save(item("scan_tool"))]


# --- Rally Banner: held upright like vanilla's banners ----------------------------------------------------------------
def rally_banner():
    """A tall standard held upright, the way vanilla shows its banners: an iron crossbar with a gold finial, a blue
    cloth with two crossed swords (gold guards, wooden grips) and a tattered hem, the foot of the pole below."""
    s = grid("""
        .......yY.......
        ...xxxxxxxxxx...
        ...nVuuuuuuVN...
        ...nuVuuuuVUN...
        ...nuuVuuVUUN...
        ...nuuuVVUUUN...
        ...nuuuVVUUUN...
        ...nuuVuuVUUN...
        ...nuVuuuuVUN...
        ...nyyyuuyyyN...
        ...nutuuuuUtN...
        ...nuuuuUUUUN...
        ...nunuuNUNUN...
        ...nn.nNN.NNN...
        .......AE.......
        .......EE.......
    """, dict(WOOD, n="#1f2f6a", N="#141d45", u="#3e4db2", U="#2d3a90", V="#f2f2ec",   # blue wool, silver blades
              y=GOLD[2], Y=GOLD[0], x="#6b6b6b", t="#5a3a18"))                            # guards, crossbar, grips
    return [s.save(item("rally_banner"))]


# --- Settler's Wagon: a side view -----------------------------------------------------------------------------------
def settlers_wagon():
    """A covered wagon in side view, facing right: the canvas bonnet with its hoops showing, a plank bed, two spoked
    wheels and the stub of the pole."""
    s = grid("""
        ................
        ................
        ....VVVVVVVV....
        ...VWWWWWWWWV...
        ..VWWvWWvWWvwV..
        ..VWwvwwvwwvwV..
        ..VwwvwwvwwvwV..
        ..VwwvwwvwwvvX..
        .OPPPPPPPPPPPPO.
        .OppppppppppppQQ
        ..kkkQQQQQkkkQ..
        .kkhkk...kkhkk..
        .khhhk...khhhk..
        .kkhkk...kkhkk..
        ..kkk.....kkk...
        ................
    """, {"W": "#f6f2e6", "w": "#e4ddc9", "v": "#c8bfa6", "V": "#8f866e", "X": "#5f5846",   # canvas
          "P": OAK[1], "p": OAK[2], "O": "#4a3a18", "Q": "#2e260c",                       # oak bed
          "k": "#3a2712", "h": OAK[0]})                                                   # wheels: rims, spokes
    return [s.save(item("settlers_wagon"))]


DRAW = [blank_blueprint, blueprint, shape_planner, patrol_map, delivery_note, travel_ticket, price_tag,
        village_ledger, field_marker, quarry_marker, rally_banner, scan_tool, settlers_wagon]

if __name__ == "__main__":
    run(DRAW)
