package io.github.jcondedata.aliveworkplace.blueprint;

import io.github.jcondedata.aliveworkplace.AliveWorkplace;
import java.util.List;
import net.minecraft.core.Vec3i;
import net.minecraft.resources.ResourceLocation;

/**
 * Builds that ship with the mod ({@code data/aliveworkplace/structure/}). Generated by
 * {@code tools/blueprints/generate.py}; keep sizes in sync when a build changes (a gametest checks this).
 */
public final class StarterBlueprints {
	public record Entry(ResourceLocation id, Vec3i size) {
	}

	public static final Entry STARTER_COTTAGE = new Entry(AliveWorkplace.id("starter_cottage"), new Vec3i(9, 10, 9));
	public static final Entry MARKET_STALL = new Entry(AliveWorkplace.id("market_stall"), new Vec3i(7, 5, 5));
	public static final Entry LOOKOUT_TOWER = new Entry(AliveWorkplace.id("lookout_tower"), new Vec3i(7, 15, 7));

	public static final List<Entry> ALL = List.of(STARTER_COTTAGE, MARKET_STALL, LOOKOUT_TOWER);

	private StarterBlueprints() {
	}
}
