"""Icon picks for four paper-family items: three new versions (v2, v3, v4) of the village ledger, delivery note, travel
ticket and price tag, each built around a different idea, for the owner to choose from. The current icon (v1) stays in
tools/textures/art/items.py. Running this writes build/texture-picks/<item>/v2.png .. v4.png and captions.json.

Every icon sits in its vanilla family (the book's diagonal pose, the paper sheet, signs, tags) and uses the colours of
items.py and of vanilla's neighbours; every shape is drawn here."""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "tools" / "textures" / "art"))

from artlib import *  # noqa: E402,F401,F403
from items import CREAM, GOLD, PAPER, on, sheet  # noqa: E402

OUT = REPO / "build" / "texture-picks"

EMERALD = P("emerald")      # 0 #007b18 .. 7 #dbffeb, outline #005300 / #002d00
COPPER = P("copper")
IRON = P("iron_tool")
RED = ("#ef6b5b", "#c62d25", "#861a15")   # wax and string red of items.py (light, face, dark)
PAGES = ("#d6d6d6", "#b7b7b7", "#999999")  # vanilla book's page edges
OAK = ("#c29d62", "#af8f55", "#967441", "#7e6237", "#614a26", "#382b18")   # oak sign: lit .. dark outline
KRAFT = Ramp(["#b8935a", "#ceac6d", "#e6c78c", "#f2dcaa"], outline=("#8a6a38", "#5c4417"), name="kraft")  # name tag tan


def save(sprite, item_name, version):
    return sprite.save(OUT / item_name / f"{version}.png")


# --- Village Ledger ---------------------------------------------------------------------------------------------------
# A closed book lying on the diagonal like vanilla's books: a = cover edge (top), o = cover edge (bottom), k = back cover,
# 2 / 1 / 0 = cover lit band, face, shade. The page block shows under the cover on both sides, as in vanilla: P / p on
# the lit side (the upper page row in the cover's shadow, the lower one lit), Q / q on the shaded side.
BOOK = """
    ................
    .........aa.....
    .......aa22a....
    .....aa22111a...
    ...aa22111111a..
    .aa22111111111a.
    a22111111111100a
    Po11111111100ooQ
    pPo11111100ooQQq
    kpPo11100ooQQqqk
    .kpPo00ooQQqqkk.
    ..kpPooQQqqkk...
    ...kpPPqqkk.....
    ....kppkk.......
    .....kk.........
    ................
"""


def book(cover, edge, back):
    """The closed book in a cover ramp of three (shade, face, lit)."""
    return grid(BOOK, {"a": edge, "o": edge, "k": back, "P": PAGES[1], "p": PAGES[0], "Q": PAGES[2], "q": PAGES[1]},
                ramp=Ramp(cover))


def ledger_v2():
    """Bound in dark red-brown leather like an old account book, a cut emerald set in gold prongs on the cover."""
    s = book(("#6a2c17", "#7d371d", "#924526"), "#4a1d0e", "#2c1006")
    on(s, """
        ................
        ................
        ................
        ................
        ......yEEy......
        ......EWgE......
        ......EggE......
        ......EgdE......
        ......yEEy......
    """, {"E": EMERALD.outline_light, "W": EMERALD[6], "g": EMERALD[4], "d": EMERALD[1], "y": GOLD[2]})
    return save(s, "village_ledger", "v2")


def ledger_v3():
    """The ledger lying open on its green cloth cover: two pages of accounts ruled with a green column line, the
    pages dipping into the gutter."""
    s = grid("""
        ................
        ..aaa......aaa..
        .a333aa..aa222d.
        ca33333aa22222dc
        caLLLg311LLLg2dc
        ca333g311222g2dc
        caLL3g311LL2g2dc
        ca333g311222g2dc
        caLLLg311LLLg2dc
        ca333g311222g2dc
        caLL3g311LL2g2dc
        cdddd331122ddddc
        kccccdd11ddcccck
        .kkkkkcddckkkkk.
        ......kkkk......
        ................
    """, {"a": PAPER.outline_light, "d": PAPER.outline_dark, "3": PAPER[3], "2": PAPER[2], "1": PAPER[1],
          "L": "#6e6a80", "g": "#1f9a3c", "c": "#306739", "k": "#0f2a15"})
    return save(s, "village_ledger", "v3")


def ledger_v4():
    """The village's register: a navy cloth book with the village bell stamped on its cover in gold."""
    s = book(("#1d3260", "#263f75", "#31508c"), "#14234a", "#0a1430")
    on(s, """
        ................
        ................
        ................
        .......Y........
        ......YYy.......
        .....YWyyz......
        .....YYyyz......
        .....Yyyyz......
        ....YYyyyzz.....
        .......z........
    """, {"W": GOLD[3], "Y": GOLD[2], "y": GOLD[1], "z": GOLD[0]})
    return save(s, "village_ledger", "v4")


# --- Delivery Note ----------------------------------------------------------------------------------------------------
def fold(s, ramp, crease):
    """Folds a sheet across its long axis: the half below-left of the crease line x - y = crease drops one shade."""
    cols = [tuple(int(v) for v in c) for c in ramp]
    for y in range(s.h):
        for x in range(s.w):
            c = tuple(int(v) for v in s.get(x, y))
            if x - y < crease and c in cols[1:]:
                s.put(x, y, cols[cols.index(c) - 1])
    return s


def note_v2():
    """A note folded in half across the sheet, a red route arrow drawn over the fold from one end to the other."""
    s = fold(sheet(PAPER), list(PAPER)[-4:], 1)
    on(s, """
        ................
        ................
        ................
        ................
        ........RRR.....
        ......f..RR.....
        .......fR.R.....
        .......Rf.......
        ......R..f......
        .....R....f.....
        ....R...........
    """, {"R": RED[1], "f": PAPER[0]})
    return save(s, "delivery_note", "v2")


def note_v3():
    """A parcel in brown paper tied crosswise with string, a white note tucked under the knot."""
    s = grid("""
        ................
        ........aaaa....
        .......a3333d...
        .......a3ii3d...
        ......oa3333d...
        ....ooTa333dTo..
        ..oossTssTTTToo.
        ..oLTTsssTTTTRO.
        ..oLLLTsssTRRRO.
        ..oLLsLLRsRRRRO.
        ..oLLsLLRsRRRRO.
        ..oLLsLLRsRRRRO.
        ..OOLsLLRsRROO..
        ....OOLLRROO....
        ......OOOO......
        ................
    """, {"o": "#5c4417", "O": "#3a2a0e", "T": "#dcbb80", "L": "#c29d62", "R": "#967441", "s": "#f7f7f7",
          "a": PAPER.outline_light, "d": PAPER.outline_dark, "3": PAPER[3], "i": "#6e6a80"})
    return save(s, "delivery_note", "v3")


def note_v4():
    """A wooden clipboard with an iron clip holding the courier's list, two jobs ticked off."""
    s = grid("""
        ................
        ......iiii......
        ..AAAAiWwiAAAA..
        ..AbbbiwwibbbE..
        ..Ab33iiii22bE..
        ..Ab32222222bE..
        ..Ab3g2LLLL2bE..
        ..Ab22222222bE..
        ..Ab2g2LLL22bE..
        ..Ab22222222bE..
        ..Ab2x2LLLL2bE..
        ..Ab22222222bE..
        ..Ab21111111bE..
        ..AbbbbbbbbbbE..
        ..EEEEEEEEEEEE..
        ................
    """, {"A": OAK[4], "E": OAK[5], "b": OAK[2], "i": IRON.outline_light, "W": IRON[3], "w": IRON[1],
          "3": PAPER[3], "2": PAPER[2], "1": PAPER[1], "L": "#5a5668", "g": "#3f8425", "x": PAPER.outline_light})
    return save(s, "delivery_note", "v4")


# --- Travel Ticket ----------------------------------------------------------------------------------------------------
def ticket_v2():
    """A cream card ticket held level, notched at both ends, a sailing boat printed on it in two blues and a stub past
    the perforation with two lines of print."""
    c = CREAM
    s = grid("""
        ................
        ................
        ................
        ..oooooooooooo..
        .o333N3333p333O.
        .o222Nn2222ii2O.
        ..o22Nnn22p22O..
        ..o22Nnnn222iO..
        ..o22N2222p22O..
        .o2NNNNNNN2ii2O.
        .o11NNNNN1p111O.
        ..OOOOOOOOOOOO..
        ................
        ................
        ................
        ................
    """, {"o": c.outline_light, "O": c.outline_dark, "3": c[3], "2": c[2], "1": c[1], "p": c.outline_light,
          "N": "#2d5fa6", "n": "#4f86cc", "i": c.outline_light})
    return save(s, "travel_ticket", "v2")


def ticket_v3():
    """A round copper ferry token with an anchor stamped in it."""
    s = grid("""
        ................
        ................
        ................
        .....aaaaa......
        ....a54443a.....
        ...a443s333b....
        ..a443s3s332b...
        ..a4333s3332b...
        ..a33sssss32b...
        ..a3333s3222b...
        ..a33s3s2s22b...
        ...a32sss22b....
        ....b22221b.....
        .....bbbbb......
        ................
        ................
    """, {"a": COPPER.outline_light, "b": COPPER.outline_dark, "s": COPPER[1]}, ramp=COPPER)
    return save(s, "travel_ticket", "v3")


def ticket_v4():
    """The ticket folded into a paper boat, as a ferry ticket might be: cream card, a sail over the hull, the
    perforation along its side."""
    c = CREAM
    s = grid("""
        ................
        ................
        ........a.......
        .......a3d......
        ......a332d.....
        .....a3322d.....
        ....a33222d.....
        ...a332221d.....
        .a.a332221d..d..
        .a3a22222111dd..
        ..a33332221111d.
        ...a3p2p2p2p1d..
        ....a1111111d...
        .....ddddddd....
        ................
        ................
    """, {"a": c.outline_light, "d": c.outline_dark, "p": c.outline_light}, ramp=c)
    return save(s, "travel_ticket", "v4")


# --- Price Tag --------------------------------------------------------------------------------------------------------
def price_v2():
    """A tan card tag hanging from a string loop, a dollar sign printed on it."""
    k = KRAFT
    s = grid("""
        ......SSS.......
        .....S...S......
        ......S.S.......
        .......S........
        .....aaSaa......
        ....a33h22d.....
        ....a32222d.....
        ....a32i21d.....
        ....a2iii1d.....
        ....a3i221d.....
        ....a2iii1d.....
        ....a322i1d.....
        ....a2iii1d.....
        ....a21i11d.....
        .....ddddd......
        ................
    """, {"a": k.outline_light, "d": k.outline_dark, "S": "#f7f7f7", "h": k.outline_dark, "i": "#5c4417"},
        ramp=k)
    return save(s, "price_tag", "v2")


def price_v3():
    """A small wooden shop sign on a post with a gold coin painted on the board."""
    s = grid("""
        ................
        ................
        .AAAAAAAAAAAAAA.
        .Arrrrrrrrrrrrr.
        .Abbbbooooobbbe.
        .AlllloYYyolllE.
        .AbbboYyyyzobbe.
        .AbbboyyyzzobbE.
        .AllllozzzolllE.
        .Abbbbbooobbbbe.
        .EEEEEEAeEEEEEE.
        .......ABe......
        .......ABe......
        .......ACe......
        .......AEe......
        ................
    """, {"A": OAK[4], "E": OAK[5], "r": OAK[0], "b": OAK[1], "l": OAK[3], "e": OAK[4], "B": OAK[2], "C": OAK[3],
          "o": GOLD.outline_light, "Y": GOLD[3], "y": GOLD[2], "z": GOLD[1]})
    return save(s, "price_tag", "v3")


def price_v4():
    """A stack of gold coins tied round with red string, a paper price tag hanging from the string beside it."""
    tag = Ramp(list(PAPER), outline=("#9a9a9a", "#6e6e6e"), name="tag")
    s = grid("""
        ................
        ................
        ..ooooo.........
        .oYYYyyo........
        .oyyyyzQ........
        .QzzzzzQ........
        .oYyyyzQ........
        .rrrrrrrr.......
        .oYyyyzQ.raa....
        .QzzzzzQ.ah3d...
        .oYyyyzQa3322d..
        .QzzzzzQa3222d..
        ..QQQQQ.a3221d..
        ........a2211d..
        .........dddd...
        ................
    """, {"a": tag.outline_light, "d": tag.outline_dark, "h": tag.outline_dark, "r": RED[1],
          "o": GOLD.outline_light, "Q": GOLD.outline_dark, "Y": GOLD[3], "y": GOLD[2], "z": GOLD[1]}, ramp=tag)
    return save(s, "price_tag", "v4")


PICKS = {
    "village_ledger": ([ledger_v2, ledger_v3, ledger_v4], {
        "v2": "Leather-bound with an emerald on the cover",
        "v3": "Open ledger with green-ruled accounts",
        "v4": "Navy register stamped with the village bell",
    }),
    "delivery_note": ([note_v2, note_v3, note_v4], {
        "v2": "Folded note with a red route arrow",
        "v3": "Parcel tied with string and a note",
        "v4": "Clipboard holding the courier's list",
    }),
    "travel_ticket": ([ticket_v2, ticket_v3, ticket_v4], {
        "v2": "Cream ticket printed with a sailing boat",
        "v3": "Round copper ferry token with an anchor",
        "v4": "Ticket folded into a paper boat",
    }),
    "price_tag": ([price_v2, price_v3, price_v4], {
        "v2": "Hanging tan tag with a dollar sign",
        "v3": "Wooden shop sign with a gold coin",
        "v4": "Gold coin stack with a hanging tag",
    }),
}


def main():
    for name, (draws, captions) in PICKS.items():
        for draw in draws:
            print("wrote", draw().relative_to(REPO))
        path = OUT / name / "captions.json"
        path.write_text(json.dumps(captions, indent=2) + "\n")
        print("wrote", path.relative_to(REPO))


if __name__ == "__main__":
    main()
