"""Alternative icons for the sheet items, for the owner to pick from: three new versions (v2, v3, v4) of the blueprint,
the blank blueprint, the shape planner and the patrol map. v1 is the current icon (tools/textures/art/items.py).

Every version is built around its own idea (a pose, an object or a composition), each from vanilla's family for that
kind of thing: sheets on the diagonal like the map and paper, a roll, a clipboard, a compass case like vanilla's, drafting
tools drawn like vanilla's tools. The blueprint family keeps the BLUE ramp of items.py; the patrol map its PARCHMENT.

    python3 tools/textures/picks/sheets.py      writes build/texture-picks/<item>/v2.png .. v4.png + captions.json
"""
import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO / "tools/textures/art"))

from artlib import *  # noqa: E402,F401,F403
from items import BLUE, GOLD, INK, PARCHMENT, ROUTE, STICK, on, sheet  # noqa: E402

OUT = REPO / "build" / "texture-picks"

# --- Shared colours ---------------------------------------------------------------------------------------------------
B = {"a": BLUE.outline_light, "d": BLUE.outline_dark}          # the blueprint outline pair
EDGE = "#78a4dc"                                                # the cut edge of rolled blueprint paper
STRING = {"w": "#ecebe4"}                                       # cotton string
IRON = {"I": "#d8d8d8", "i": "#a8a8a8", "j": "#727272", "k": "#444444", "K": "#2b2b2b"}   # vanilla iron
OAK = {"P": "#c29d62", "p": "#af8f55", "q": "#967441", "A": STICK.outline_light, "E": STICK.outline_dark}
BRASS = {"Y": GOLD[3], "y": GOLD[2], "z": GOLD[1], "o": GOLD.outline_light, "O": GOLD.outline_dark}
PA = {"a": PARCHMENT.outline_light, "d": PARCHMENT.outline_dark}


def bp(art, legend=None):
    """A grid in the blueprint ramp: digits 0-3 are BLUE, a/d its outline pair."""
    return grid(art, dict(B, **(legend or {})), ramp=BLUE)


def pm(art, legend=None):
    """A grid in the parchment ramp: digits 0-3 are PARCHMENT, a/d its outline pair."""
    return grid(art, dict(PA, **(legend or {})), ramp=PARCHMENT)


# --- Blueprint ------------------------------------------------------------------------------------------------------
# A roll lying on the diagonal like a tool, lit from the top-left: a/d its outline pair, 3 the lit stripe, 1 the
# shaded side; L and c the near end (the cut edge of the rolled sheet round a dark centre), w two turns of string.
ROLL = """
    ................
    ................
    ..........aa....
    .........a23d...
    ........a2322d..
    .......aw3221d..
    ......aw3w21d...
    .....a23w2wd....
    ....a2322wd.....
    ...aaa221d......
    ..aLLLd1d.......
    ..aLccdd........
    ..aLLLd.........
    ...ddd..........
    ................
    ................
"""


def blueprint_v2():
    """Rolled up and tied: a fat roll of blueprint paper on the diagonal, its near end showing the spiral of the
    rolled sheet, two turns of cotton string round its middle."""
    return bp(ROLL, dict(STRING, L=EDGE, c=BLUE[0]))


PENCIL = {"Y": "#f4cf5e", "y": "#e9b53a", "o": "#a8741a", "O": "#6e4a0e",      # yellow body and its outline
          "t": "#d7b98a", "g": "#3a3a44",                                       # sharpened wood, graphite point
          "m": "#c1c1c1", "q": "#b8506f", "e": "#e6789c"}                      # ferrule, eraser


def blueprint_v3():
    """The blueprint sheet with its house, and a yellow pencil lying across it, its point at the corner it is drawing.
    Drawn like vanilla's sticks: a lit outline, one pixel of colour, a shadow outline on each row."""
    s = on(sheet(BLUE), """
        ................
        ................
        ................
        ................
        .......w.w......
        ......w.ww......
        .....w...w......
        ....wwwwwww.....
        .....w...w......
        .....w.w.w......
        .....wwwww......
    """, {"w": INK})
    return on(s, """
        ................
        ................
        ................
        ................
        ................
        .............qO.
        ............qeO.
        ...........omO..
        ..........oYO...
        .........oyO....
        ........oYO.....
        .......otO......
        .......g........
    """, PENCIL)


def blueprint_v4():
    """Clipped to a wooden drawing board: an oak board, the blue sheet on it with the house of v1, an iron clip at the
    top."""
    return grid("""
        ................
        ......kkkk......
        ..AAAkIIijkAAA..
        ..APPkIiijkPPE..
        ..AP3KKKKKK3qE..
        ..AP322w2w21qE..
        ..AP32w2ww21qE..
        ..AP3w222w21qE..
        ..APwwwwwww1qE..
        ..AP3w222w21qE..
        ..AP3w2w2w21qE..
        ..AP3wwwww21qE..
        ..AP31111111qE..
        ..APqqqqqqqqqE..
        ..EEEEEEEEEEEE..
        ................
    """, dict(OAK, **IRON, w=INK, **{"1": BLUE[1], "2": BLUE[2], "3": BLUE[3]}))


# --- Blank blueprint ------------------------------------------------------------------------------------------------
# A smaller sheet in the same pose as items.SHEET (long edges stepping 2-1, short edges at 45 degrees), for two to fit.
SMALL_SHEET = """
    .........aa.....
    .......aa33a....
    ......a33223a...
    ....aa3222223a..
    ...a322222221d..
    ...d1222221dd...
    ....d12221d.....
    .....d121d......
    ......dd........
"""


def blank_blueprint_v2():
    """Two sheets, one lying on the other (paper and blue dye make two)."""
    under = Ramp([BLUE[0], BLUE[0], BLUE[1], BLUE[2]], outline=(BLUE.outline_light, BLUE.outline_dark))
    s = Sprite()
    s.paste(sheet(under, SMALL_SHEET), 1, 5)        # the lower sheet, a step darker in the upper one's shade
    s.paste(sheet(BLUE, SMALL_SHEET), -1, 2)
    return s


def blank_blueprint_v3():
    """Half unrolled: a roll of blank blueprint paper along one edge, the rest of the sheet lying flat beside it."""
    return bp("""
        ................
        ................
        ........aa......
        .......a3d......
        ......a321d.....
        .....a321d3d....
        ....a321d223d...
        ..aa321d22222d..
        .aLLd1d2222221d.
        .aLcdd222222dd..
        ..ddda22221d....
        ......a221d.....
        .......a1d......
        ........d.......
        ................
        ................
    """, dict(L=EDGE, c=BLUE[0]))


def blank_blueprint_v4():
    """The blank sheet with its right corner folded over, showing the paler back of the paper; the flap shades a line
    of the sheet along its edge (s)."""
    return bp("""
        ................
        ................
        .........aa.....
        .......aa33a....
        ......a33Fa.....
        ....aa322FFa....
        ...a3322sFFFa...
        .aa32222sFFffd..
        .d1222222sfdd...
        ..d12222211d....
        ...d12221dd.....
        ....d121d.......
        .....d1d........
        ......dd........
        ................
        ................
    """, {"F": "#b9d0ee", "f": "#8fb2e2", "s": BLUE[0]})


# --- Shape planner --------------------------------------------------------------------------------------------------
def shape_planner_v2():
    """The brass drafting compass on its own, legs apart: a steel point on one foot, a pencil lead on the other."""
    return grid("""
        ................
        .......oo.......
        ......oYyo......
        .....oYyyzo.....
        .....oyzzzO.....
        ......oyzO......
        .....oyOoyO.....
        .....oyO.oyO....
        ....oyO..oyO....
        ....oyO...oyO...
        ...oyO....oyO...
        ...oyO.....oyO..
        ..oyO......gGO..
        ..nN........gG..
        ..n.............
        ................
    """, dict(BRASS, n="#d8d8d8", N="#6b6b6b", g="#565664", G="#3a3a44"))


def shape_planner_v3():
    """A compass case like vanilla's, iron, with a blueprint dial: a dome drawn in white where the needle would be."""
    return grid("""
        ................
        ................
        .....OOOOOO.....
        ...OOooooooOO...
        ..Oo11111111oO..
        .Oo1222ww2222oO.
        .Oo122w22w222oO.
        .Oo12w2222w22oO.
        .Oo12wwwwww22oO.
        .OYo22222222oZO.
        .OYYyyyZZZZZZzO.
        ..OYYyyZZZZzzO..
        ...OOzzzzzzOO...
        .....OOOOOO.....
        ................
        ................
    """, {"O": "#181717", "o": "#353535", "y": "#a8a8a8", "Y": "#d8d8d8", "z": "#5e5e5e", "Z": "#828282", "w": INK,
          "1": BLUE[1], "2": BLUE[2]})


def shape_planner_v4():
    """A set square in blueprint blue, the triangle cut out of its middle, white marks along its two short edges
    counting out from the right angle."""
    return bp("""
        ................
        .a..............
        .aa.............
        .a3a............
        .aw3a...........
        .a332a..........
        .a32d3a.........
        .aw2.d3a........
        .a32..d3a.......
        .a32...d3a......
        .aw2....d3a.....
        .a32aaaaaa32a...
        .a32333333221a..
        .a222w22w22w11d.
        .dddddddddddddd.
        ................
    """, {"w": INK})


# --- Patrol map -----------------------------------------------------------------------------------------------------
def patrol_map_v2():
    """A guard's shield, blue with a gold boss like the Guard Post's, at the start of a red patrol loop."""
    return on(sheet(PARCHMENT), """
        ................
        ................
        ................
        ................
        .......RR.R.....
        ...........R....
        ...kkkkk.....R..
        ...kBbbk....R...
        ...kbYbk...R....
        ...kbbbk.RR.....
        ....kbk.........
        .....k..........
    """, {"R": ROUTE, "k": "#1f3352", "b": BLUE[2], "B": BLUE[3], "Y": GOLD[2]})


def patrol_map_v3():
    """Rolled up like the blueprint roll, in parchment, tied with two turns of red string (the red dye)."""
    return pm(ROLL, {"w": "#d9362b", "L": "#fbf6e6", "c": PARCHMENT[0]})


def patrol_map_v4():
    """A folded map in three panels, the red route running across the folds to a cross."""
    return on(pm("""
        ................
        ................
        ................
        ....aaa......aa.
        ..aa331aa..aa2d.
        .a3333111aa222d.
        .a333311102222d.
        .a333311102222d.
        .a333311102222d.
        .a333311102222d.
        .a333311102222d.
        .a33ddd110222dd.
        .add...dd02dd...
        .d.......dd.....
        ................
        ................
    """), """
        ................
        ................
        ................
        ................
        ................
        ...........R.R..
        ............R...
        ..........RR.R..
        ........R.......
        .......R........
        .....R..........
        ...RR...........
        ..R.............
    """, {"R": ROUTE})


ITEMS = {
    "blueprint": {
        "v2": (blueprint_v2, "Rolled up and tied with string"),
        "v3": (blueprint_v3, "Sheet with a pencil drawing the house"),
        "v4": (blueprint_v4, "Clipped to a wooden drawing board"),
    },
    "blank_blueprint": {
        "v2": (blank_blueprint_v2, "Two blank sheets, one on another"),
        "v3": (blank_blueprint_v3, "Half unrolled, the rest lying flat"),
        "v4": (blank_blueprint_v4, "Corner folded over, pale back showing"),
    },
    "shape_planner": {
        "v2": (shape_planner_v2, "Brass drafting compass on its own"),
        "v3": (shape_planner_v3, "Iron compass case with a blueprint dial"),
        "v4": (shape_planner_v4, "Blue set square with ruler marks"),
    },
    "patrol_map": {
        "v2": (patrol_map_v2, "Guard's shield starting a patrol loop"),
        "v3": (patrol_map_v3, "Rolled up, tied with red string"),
        "v4": (patrol_map_v4, "Folded map, route across the folds"),
    },
}


def main():
    for name, versions in ITEMS.items():
        folder = OUT / name
        folder.mkdir(parents=True, exist_ok=True)
        for ver, (draw, _) in versions.items():
            path = draw().save(folder / f"{ver}.png")
            print("wrote", path.relative_to(REPO))
        captions = {ver: caption for ver, (_, caption) in versions.items()}
        (folder / "captions.json").write_text(json.dumps(captions, indent=2) + "\n")


if __name__ == "__main__":
    main()
